version: "2"
services:
  app:
    build: .
    command: idle
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./test:/app/test
      - ./stack.yaml:/app/stack.yaml
      - ./nippoa.cabal:/app/nippoa.cabal
